info:
  contact:
    email: ast9501.cs10@nycu.edu.tw
    name: ast9501
  description: winlab O-RAN NFO
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: O-RAN NFO api doc
  version: "1.0"
paths:
  /nfo/v1/:
    get:
      description: health check for api server
      responses:
        "200":
          description: OK
      summary: root path
swagger: "2.0"
